import type { Metadata } from "next";
import { Geist, Geist_Mono ,  Source_Serif_4 } from "next/font/google";
import Providers from "@/components/Providers"
import "./globals.css";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import TrendingMovies from  "@/components/TrendingMovies";
import TrendingSeries from "@/components/TrendingSeries";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body  className={`${sourceSerif.className} bg-black`}>
        <Providers>
          <Header/>
          <HeroSection/>
          <TrendingMovies/>
          <TrendingSeries/>
          {children}
        </Providers>
        </body>
    </html>
  );
}
